services:
  todo-main-api:
    build:
      context: .
      dockerfile: ./apps/todo-main-api/Dockerfile
      target: development
    command: yarn start:dev todo-main-api
    env_file:
      - ./apps/todo-main-api/.env
    ports:
      - '3000:3000'
    volumes:
    - .:/usr/src/app
    depends_on:
     - todo-main-api-db

  todo-history-persistence:
    build:
      context: .
      dockerfile: ./apps/todo-history-persistence/Dockerfile
      target: development
    command: yarn start:dev todo-history-persistence
    env_file:
      - ./apps/todo-history-persistence/.env
    ports:
      - '5555:5555'
    volumes:
    - .:/usr/src/app
    depends_on:
     - todo-history-persistence-db

  todo-main-api-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo-main
    ports:
      - "3307:3306"

  todo-history-persistence-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: history-persistence
    ports:
      - "3308:3306"
